In [ ]:
'''

Make two tables for Feature Information + Paper Information 
And Relate two tables

-1970
1970-1980
1980-1990
1990-2000
2000-2005
2005-2010
2010-2015
2015-2018


+ Add Queried date

+ share polygon coordinate problem 

'''

In [95]:
import pandas as pd
import json
import csv
import numpy as np
from datetime import date

In [10]:
data_frame = pd.read_csv('mars_gaz.csv', index_col = False)

In [11]:
attr_feature = data_frame[['Feature_ID', 'Clean_Feature_Name', 'Target',
       'Diameter', 'Center_Latitude', 'Center_Longitude', 'Northern_Latitude',
       'Southern_Latitude', 'Eastern_Longitude', 'Western_Longitude',
       'Continent', 'Ethnicity', 'Feature_Type', 'Feature_Type_Code', 'Quad',
       'Approval_Status', 'Approval_Date', 'Reference', 'Origin']]

In [12]:
polygon = data_frame['polygon']

In [89]:
import ads
q = ads.SearchQuery(q='Abus Vallis', keyword='mars', fl=['bibcode'], rows=2000)
bibcodes = [j.bibcode for j in q]
metrics_query = ads.MetricsQuery(bibcodes)
metrics_response = metrics_query.execute()
metrics_response

{'basic stats': {'average number of downloads': 5.4,
  'average number of reads': 22.8,
  'median number of downloads': 4.0,
  'median number of reads': 7.0,
  'normalized paper count': 2.25,
  'number of papers': 5,
  'recent number of downloads': 0,
  'recent number of reads': 2,
  'total number of downloads': 27,
  'total number of reads': 114},
 'basic stats refereed': {'average number of downloads': 17.0,
  'average number of reads': 50.0,
  'median number of downloads': 17.0,
  'median number of reads': 50.0,
  'normalized paper count': 0.5,
  'number of papers': 1,
  'recent number of downloads': 0,
  'recent number of reads': 1,
  'total number of downloads': 17,
  'total number of reads': 50},
 'citation stats': {'average number of citations': 1.6,
  'average number of refereed citations': 1.2,
  'median number of citations': 0.0,
  'median number of refereed citations': 0.0,
  'normalized number of citations': 3.5,
  'normalized number of refereed citations': 2.5,
  'number of citing papers': 8,
  'number of self-citations': 0,
  'self-citations': [],
  'total number of citations': 8,
  'total number of refereed citations': 6},
 'citation stats refereed': {'average number of citations': 6.0,
  'average number of refereed citations': 4.0,
  'median number of citations': 6.0,
  'median number of refereed citations': 4.0,
  'normalized number of citations': 3.0,
  'normalized number of refereed citations': 2.0,
  'number of citing papers': 6,
  'number of self-citations': 0,
  'total number of citations': 6,
  'total number of refereed citations': 4},
 'histograms': {'citations': {'nonrefereed to nonrefereed': {'1987': 0,
    '1988': 0,
    '1989': 0,
    '1990': 0,
    '1991': 0,
    '1992': 0,
    '1993': 0,
    '1994': 0,
    '1995': 0,
    '1996': 0,
    '1997': 0,
    '1998': 0,
    '1999': 0,
    '2000': 0,
    '2001': 0,
    '2002': 0,
    '2003': 0,
    '2004': 0,
    '2005': 0,
    '2006': 0,
    '2007': 0,
    '2008': 0,
    '2009': 0,
    '2010': 0,
    '2011': 0,
    '2012': 0,
    '2013': 0,
    '2014': 0,
    '2015': 0,
    '2016': 0,
    '2017': 0},
   'nonrefereed to nonrefereed normalized': {'1987': 0,
    '1988': 0,
    '1989': 0,
    '1990': 0,
    '1991': 0,
    '1992': 0,
    '1993': 0,
    '1994': 0,
    '1995': 0,
    '1996': 0,
    '1997': 0,
    '1998': 0,
    '1999': 0,
    '2000': 0,
    '2001': 0,
    '2002': 0,
    '2003': 0,
    '2004': 0,
    '2005': 0,
    '2006': 0,
    '2007': 0,
    '2008': 0,
    '2009': 0,
    '2010': 0,
    '2011': 0,
    '2012': 0,
    '2013': 0,
    '2014': 0,
    '2015': 0,
    '2016': 0,
    '2017': 0},
   'nonrefereed to refereed': {'1987': 0,
    '1988': 0,
    '1989': 0,
    '1990': 0,
    '1991': 0,
    '1992': 0,
    '1993': 0,
    '1994': 0,
    '1995': 0,
    '1996': 0,
    '1997': 0,
    '1998': 0,
    '1999': 0,
    '2000': 0,
    '2001': 0,
    '2002': 0,
    '2003': 0,
    '2004': 0,
    '2005': 0,
    '2006': 0,
    '2007': 2,
    '2008': 0,
    '2009': 0,
    '2010': 0,
    '2011': 0,
    '2012': 0,
    '2013': 0,
    '2014': 0,
    '2015': 0,
    '2016': 0,
    '2017': 0},
   'nonrefereed to refereed normalized': {'1987': 0,
    '1988': 0,
    '1989': 0,
    '1990': 0,
    '1991': 0,
    '1992': 0,
    '1993': 0,
    '1994': 0,
    '1995': 0,
    '1996': 0,
    '1997': 0,
    '1998': 0,
    '1999': 0,
    '2000': 0,
    '2001': 0,
    '2002': 0,
    '2003': 0,
    '2004': 0,
    '2005': 0,
    '2006': 0,
    '2007': 1.0,
    '2008': 0,
    '2009': 0,
    '2010': 0,
    '2011': 0,
    '2012': 0,
    '2013': 0,
    '2014': 0,
    '2015': 0,
    '2016': 0,
    '2017': 0},
   'refereed to nonrefereed': {'1987': 1,
    '1988': 0,
    '1989': 0,
    '1990': 1,
    '1991': 0,
    '1992': 0,
    '1993': 0,
    '1994': 0,
    '1995': 0,
    '1996': 0,
    '1997': 0,
    '1998': 0,
    '1999': 0,
    '2000': 0,
    '2001': 0,
    '2002': 0,
    '2003': 0,
    '2004': 0,
    '2005': 0,
    '2006': 0,
    '2007': 0,
    '2008': 0,
    '2009': 0,
    '2010': 0,
    '2011': 0,
    '2012': 0,
    '2013': 0,
    '2014': 0,
    '2015': 0,
    '2016': 0,
    '2017': 0},
   'refereed to nonrefereed normalized': {'1987': 0.25,
    '1988': 0,
    '1989': 0,
    '1990': 0.25,
    '1991': 0,
    '1992': 0,
    '1993': 0,
    '1994': 0,
    '1995': 0,
    '1996': 0,
    '1997': 0,
    '1998': 0,
    '1999': 0,
    '2000': 0,
    '2001': 0,
    '2002': 0,
    '2003': 0,
    '2004': 0,
    '2005': 0,
    '2006': 0,
    '2007': 0,
    '2008': 0,
    '2009': 0,
    '2010': 0,
    '2011': 0,
    '2012': 0,
    '2013': 0,
    '2014': 0,
    '2015': 0,
    '2016': 0,
    '2017': 0},
   'refereed to refereed': {'1987': 0,
    '1988': 0,
    '1989': 0,
    '1990': 0,
    '1991': 0,
    '1992': 0,
    '1993': 1,
    '1994': 0,
    '1995': 0,
    '1996': 1,
    '1997': 0,
    '1998': 0,
    '1999': 0,
    '2000': 0,
    '2001': 1,
    '2002': 0,
    '2003': 0,
    '2004': 0,
    '2005': 0,
    '2006': 0,
    '2007': 1,
    '2008': 0,
    '2009': 0,
    '2010': 0,
    '2011': 0,
    '2012': 0,
    '2013': 0,
    '2014': 0,
    '2015': 0,
    '2016': 0,
    '2017': 0},
   'refereed to refereed normalized': {'1987': 0,
    '1988': 0,
    '1989': 0,
    '1990': 0,
    '1991': 0,
    '1992': 0,
    '1993': 0.5,
    '1994': 0,
    '1995': 0,
    '1996': 0.5,
    '1997': 0,
    '1998': 0,
    '1999': 0,
    '2000': 0,
    '2001': 0.5,
    '2002': 0,
    '2003': 0,
    '2004': 0,
    '2005': 0,
    '2006': 0,
    '2007': 0.5,
    '2008': 0,
    '2009': 0,
    '2010': 0,
    '2011': 0,
    '2012': 0,
    '2013': 0,
    '2014': 0,
    '2015': 0,
    '2016': 0,
    '2017': 0}},
  'downloads': {'all downloads': {'1996': 0,
    '1997': 0,
    '1998': 0,
    '1999': 0,
    '2000': 1,
    '2001': 0,
    '2002': 3,
    '2003': 0,
    '2004': 1,
    '2005': 0,
    '2006': 4,
    '2007': 4,
    '2008': 3,
    '2009': 2,
    '2010': 2,
    '2011': 1,
    '2012': 3,
    '2013': 2,
    '2014': 1,
    '2015': 0,
    '2016': 0,
    '2017': 0},
   'all downloads normalized': {'1996': 0.0,
    '1997': 0.0,
    '1998': 0.0,
    '1999': 0.0,
    '2000': 0.25,
    '2001': 0.0,
    '2002': 1.5,
    '2003': 0.0,
    '2004': 1.0,
    '2005': 0.0,
    '2006': 2.5,
    '2007': 1.75,
    '2008': 1.5,
    '2009': 1.0,
    '2010': 1.0,
    '2011': 0.5,
    '2012': 1.5,
    '2013': 1.0,
    '2014': 0.5,
    '2015': 0.0,
    '2016': 0.0,
    '2017': 0.0},
   'refereed downloads': {'1996': 0,
    '1997': 0,
    '1998': 0,
    '1999': 0,
    '2000': 0,
    '2001': 0,
    '2002': 0,
    '2003': 0,
    '2004': 0,
    '2005': 0,
    '2006': 0,
    '2007': 3,
    '2008': 3,
    '2009': 2,
    '2010': 2,
    '2011': 1,
    '2012': 3,
    '2013': 2,
    '2014': 1,
    '2015': 0,
    '2016': 0,
    '2017': 0},
   'refereed downloads normalized': {'1996': 0.0,
    '1997': 0.0,
    '1998': 0.0,
    '1999': 0.0,
    '2000': 0.0,
    '2001': 0.0,
    '2002': 0.0,
    '2003': 0.0,
    '2004': 0.0,
    '2005': 0.0,
    '2006': 0.0,
    '2007': 1.5,
    '2008': 1.5,
    '2009': 1.0,
    '2010': 1.0,
    '2011': 0.5,
    '2012': 1.5,
    '2013': 1.0,
    '2014': 0.5,
    '2015': 0.0,
    '2016': 0.0,
    '2017': 0.0}},
  'publications': {'all publications': {'1986': 1,
    '1987': 0,
    '1988': 1,
    '1989': 0,
    '1990': 1,
    '1991': 0,
    '1992': 0,
    '1993': 0,
    '1994': 0,
    '1995': 0,
    '1996': 0,
    '1997': 0,
    '1998': 0,
    '1999': 0,
    '2000': 0,
    '2001': 0,
    '2002': 1,
    '2003': 0,
    '2004': 0,
    '2005': 0,
    '2006': 0,
    '2007': 0,
    '2008': 0,
    '2009': 0,
    '2010': 0,
    '2011': 0,
    '2012': 1,
    '2013': 0,
    '2014': 0,
    '2015': 0,
    '2016': 0,
    '2017': 0},
   'all publications normalized': {'1986': 0.25,
    '1987': 0,
    '1988': 1.0,
    '1989': 0,
    '1990': 0.5,
    '1991': 0,
    '1992': 0,
    '1993': 0,
    '1994': 0,
    '1995': 0,
    '1996': 0,
    '1997': 0,
    '1998': 0,
    '1999': 0,
    '2000': 0,
    '2001': 0,
    '2002': 0.16666666666666666,
    '2003': 0,
    '2004': 0,
    '2005': 0,
    '2006': 0,
    '2007': 0,
    '2008': 0,
    '2009': 0,
    '2010': 0,
    '2011': 0,
    '2012': 0.3333333333333333,
    '2013': 0,
    '2014': 0,
    '2015': 0,
    '2016': 0,
    '2017': 0},
   'refereed publications': {'1986': 0,
    '1987': 0,
    '1988': 0,
    '1989': 0,
    '1990': 1,
    '1991': 0,
    '1992': 0,
    '1993': 0,
    '1994': 0,
    '1995': 0,
    '1996': 0,
    '1997': 0,
    '1998': 0,
    '1999': 0,
    '2000': 0,
    '2001': 0,
    '2002': 0,
    '2003': 0,
    '2004': 0,
    '2005': 0,
    '2006': 0,
    '2007': 0,
    '2008': 0,
    '2009': 0,
    '2010': 0,
    '2011': 0,
    '2012': 0,
    '2013': 0,
    '2014': 0,
    '2015': 0,
    '2016': 0,
    '2017': 0},
   'refereed publications normalized': {'1986': 0,
    '1987': 0,
    '1988': 0,
    '1989': 0,
    '1990': 0.5,
    '1991': 0,
    '1992': 0,
    '1993': 0,
    '1994': 0,
    '1995': 0,
    '1996': 0,
    '1997': 0,
    '1998': 0,
    '1999': 0,
    '2000': 0,
    '2001': 0,
    '2002': 0,
    '2003': 0,
    '2004': 0,
    '2005': 0,
    '2006': 0,
    '2007': 0,
    '2008': 0,
    '2009': 0,
    '2010': 0,
    '2011': 0,
    '2012': 0,
    '2013': 0,
    '2014': 0,
    '2015': 0,
    '2016': 0,
    '2017': 0}},
  'reads': {'all reads': {'1996': 0,
    '1997': 0,
    '1998': 0,
    '1999': 0,
    '2000': 1,
    '2001': 0,
    '2002': 3,
    '2003': 11,
    '2004': 14,
    '2005': 5,
    '2006': 11,
    '2007': 24,
    '2008': 5,
    '2009': 6,
    '2010': 11,
    '2011': 1,
    '2012': 5,
    '2013': 4,
    '2014': 5,
    '2015': 3,
    '2016': 3,
    '2017': 2},
   'all reads normalized': {'1996': 0.0,
    '1997': 0.0,
    '1998': 0.0,
    '1999': 0.0,
    '2000': 0.25,
    '2001': 0.0,
    '2002': 1.5,
    '2003': 1.8333333333333333,
    '2004': 3.833333333333333,
    '2005': 2.0,
    '2006': 4.666666666666667,
    '2007': 9.166666666666666,
    '2008': 2.1666666666666665,
    '2009': 2.3333333333333335,
    '2010': 4.833333333333333,
    '2011': 0.5,
    '2012': 2.1666666666666665,
    '2013': 2.0,
    '2014': 1.8333333333333333,
    '2015': 1.3333333333333333,
    '2016': 0.6666666666666666,
    '2017': 0.8333333333333333},
   'refereed reads': {'1996': 0,
    '1997': 0,
    '1998': 0,
    '1999': 0,
    '2000': 0,
    '2001': 0,
    '2002': 0,
    '2003': 0,
    '2004': 2,
    '2005': 1,
    '2006': 3,
    '2007': 15,
    '2008': 4,
    '2009': 4,
    '2010': 9,
    '2011': 1,
    '2012': 4,
    '2013': 4,
    '2014': 2,
    '2015': 0,
    '2016': 0,
    '2017': 1},
   'refereed reads normalized': {'1996': 0.0,
    '1997': 0.0,
    '1998': 0.0,
    '1999': 0.0,
    '2000': 0.0,
    '2001': 0.0,
    '2002': 0.0,
    '2003': 0.0,
    '2004': 1.0,
    '2005': 0.5,
    '2006': 1.5,
    '2007': 7.5,
    '2008': 2.0,
    '2009': 2.0,
    '2010': 4.5,
    '2011': 0.5,
    '2012': 2.0,
    '2013': 2.0,
    '2014': 1.0,
    '2015': 0.0,
    '2016': 0.0,
    '2017': 0.5}}},
 'indicators': {'g': 2,
  'h': 2,
  'i10': 0,
  'i100': 0,
  'm': 0.0625,
  'read10': 0.35889872173058013,
  'riq': 15,
  'tori': 0.17846076454906004},
 'indicators refereed': {'g': 1,
  'h': 1,
  'i10': 0,
  'i100': 0,
  'm': 0.03125,
  'read10': 0.0,
  'riq': 15,
  'tori': 0.1644285064845439},
 'skipped bibcodes': [],
 'time series': {'g': {'1986': 0,
   '1987': 0,
   '1988': 0,
   '1989': 0,
   '1990': 1,
   '1991': 1,
   '1992': 1,
   '1993': 1,
   '1994': 1,
   '1995': 1,
   '1996': 1,
   '1997': 1,
   '1998': 1,
   '1999': 1,
   '2000': 1,
   '2001': 1,
   '2002': 1,
   '2003': 1,
   '2004': 1,
   '2005': 1,
   '2006': 1,
   '2007': 1,
   '2008': 1,
   '2009': 1,
   '2010': 1,
   '2011': 1,
   '2012': 1,
   '2013': 1,
   '2014': 1,
   '2015': 1,
   '2016': 1,
   '2017': 1},
  'h': {'1986': 0,
   '1987': 0,
   '1988': 0,
   '1989': 0,
   '1990': 0,
   '1991': 0,
   '1992': 0,
   '1993': 1,
   '1994': 1,
   '1995': 1,
   '1996': 1,
   '1997': 1,
   '1998': 1,
   '1999': 1,
   '2000': 1,
   '2001': 1,
   '2002': 1,
   '2003': 1,
   '2004': 1,
   '2005': 1,
   '2006': 1,
   '2007': 1,
   '2008': 1,
   '2009': 1,
   '2010': 1,
   '2011': 1,
   '2012': 1,
   '2013': 1,
   '2014': 1,
   '2015': 1,
   '2016': 1,
   '2017': 1},
  'i10': {'1986': 0,
   '1987': 0,
   '1988': 0,
   '1989': 0,
   '1990': 0,
   '1991': 0,
   '1992': 0,
   '1993': 0,
   '1994': 0,
   '1995': 0,
   '1996': 0,
   '1997': 0,
   '1998': 0,
   '1999': 0,
   '2000': 0,
   '2001': 0,
   '2002': 0,
   '2003': 0,
   '2004': 0,
   '2005': 0,
   '2006': 0,
   '2007': 0,
   '2008': 0,
   '2009': 0,
   '2010': 0,
   '2011': 0,
   '2012': 0,
   '2013': 0,
   '2014': 0,
   '2015': 0,
   '2016': 0,
   '2017': 0},
  'i100': {'1986': 0,
   '1987': 0,
   '1988': 0,
   '1989': 0,
   '1990': 0,
   '1991': 0,
   '1992': 0,
   '1993': 0,
   '1994': 0,
   '1995': 0,
   '1996': 0,
   '1997': 0,
   '1998': 0,
   '1999': 0,
   '2000': 0,
   '2001': 0,
   '2002': 0,
   '2003': 0,
   '2004': 0,
   '2005': 0,
   '2006': 0,
   '2007': 0,
   '2008': 0,
   '2009': 0,
   '2010': 0,
   '2011': 0,
   '2012': 0,
   '2013': 0,
   '2014': 0,
   '2015': 0,
   '2016': 0,
   '2017': 0},
  'read10': {'1986': 0.0,
   '1987': 0.0,
   '1988': 0.0,
   '1989': 0.0,
   '1990': 0.0,
   '1991': 0.0,
   '1992': 0.0,
   '1993': 0.0,
   '1994': 0.0,
   '1995': 0.0,
   '1996': 0.0,
   '1997': 0.0,
   '1998': 0.0,
   '1999': 0.0,
   '2000': 0,
   '2001': 0,
   '2002': 0.0,
   '2003': 1.8333333333333333,
   '2004': 1.8333333333333333,
   '2005': 0.5,
   '2006': 0.6666666666666666,
   '2007': 1.1666666666666667,
   '2008': 0.16666666666666666,
   '2009': 0.3333333333333333,
   '2010': 0.3333333333333333,
   '2011': 0.0,
   '2012': 0.0,
   '2013': 0.0,
   '2014': 0.6666666666666666,
   '2015': 0.0,
   '2016': 0.3333333333333333,
   '2017': 0.35889872173058013},
  'tori': {'1986': 0.0,
   '1987': 0.004032258064516129,
   '1988': 0.004032258064516129,
   '1989': 0.004032258064516129,
   '1990': 0.014032258064516129,
   '1991': 0.014032258064516129,
   '1992': 0.014032258064516129,
   '1993': 0.024670555936856554,
   '1994': 0.024670555936856554,
   '1995': 0.024670555936856554,
   '1996': 0.029621050986361502,
   '1997': 0.029621050986361502,
   '1998': 0.029621050986361502,
   '1999': 0.029621050986361502,
   '2000': 0.029621050986361502,
   '2001': 0.0329323092645072,
   '2002': 0.0329323092645072,
   '2003': 0.0329323092645072,
   '2004': 0.0329323092645072,
   '2005': 0.0329323092645072,
   '2006': 0.0329323092645072,
   '2007': 0.17846076454906004,
   '2008': 0.17846076454906004,
   '2009': 0.17846076454906004,
   '2010': 0.17846076454906004,
   '2011': 0.17846076454906004,
   '2012': 0.17846076454906004,
   '2013': 0.17846076454906004,
   '2014': 0.17846076454906004,
   '2015': 0.17846076454906004,
   '2016': 0.17846076454906004,
   '2017': 0.17846076454906004}}}

In [127]:
metrics_query.response.get_ratelimits()

{'limit': '10000', 'remaining': '10000', 'reset': '1512502286'}

In [118]:
import time
today = time.strftime("%d/%m/%Y")

In [128]:
np_sum = [] #Number of Papers
ncp_sum = [] #number of citing papers
nsc_sum = [] #number of self citations
tnc_sum = [] #Total number of citations
tnrc_sum = [] #Total number of refereed citations
query_date = [] # Query Date

for i in attr_feature['Clean_Feature_Name']:
    query_date.append(today)
    q = ads.SearchQuery(q=i, keyword='mars', fl=['bibcode'], rows=3000)
    bibcodes = [j.bibcode for j in q]
    metrics_query = ads.MetricsQuery(bibcodes)
    try:        
        metrics_response = metrics_query.execute()
        np_sum.append(metrics_response['basic stats']['number of papers'])
        ncp_sum.append(metrics_response['citation stats']['number of citing papers'])
        nsc_sum.append(metrics_response['citation stats']['number of self-citations'])
        tnc_sum.append(metrics_response['citation stats']['total number of citations'])
        tnrc_sum.append(metrics_response['citation stats']['total number of refereed citations'])
        print(i + " added")
    except:
        np_sum.append(0)
        ncp_sum.append(0)
        nsc_sum.append(0)
        tnc_sum.append(0)
        tnrc_sum.append(0)
        print(i + " added with exception")

Abalos Colles added
Abalos Mensa added
Abalos Scopuli added
Abalos Undae added
Aban added
Abus Vallis added
Achar added
Acheron Catena added
Acheron Fossae added
Acidalia Colles added
Acidalia Mensa added
Acidalia Planitia added
Ada added
Adamas Labyrinthus added
Adams added
Aeolis added
Aeolis Dorsa added
Aeolis Mensae added
Aeolis Mons added
Aeolis Palus added
Aeolis Planum added
Aeolis Serpens added
Aeria added
Aesacus Dorsum added with exception
Aetheria added
Aethiopis added
Aganippe Fossa added
Agassiz added
Airy added
Airy 0 added
Ajon added with exception
Aki added
Aktaj added with exception
Alamos added
Alba Catena added
Alba Fossae added
Alba Mons added
Albany added
Alba Patera added
Albi added
Albor Fossae added
Albor Tholus added
Alexey Tolstoy added with exception
Alga added
Alitus added with exception
Allegheny Vallis added
Alnif added
Alpheus Colles added
Al Qahira Vallis added
Amazonis added
Amazonis Mensa added
Amazonis Planitia added
Amazonis Sulci added
Amenthes added
Amenthes Cavi added
Amenthes Fossae added
Amenthes Planum added
Amenthes Rupes added
Amet added with exception
Ammonii Rupes added with exception
Amphitrites Patera added
Amsterdam added
Andapa added with exception
Angu added
Angusta Patera added
Angustus Labyrinthus added
Aniak added with exception
Anio Valles added with exception
Annapolis added
Anseris Cavus added
Anseris Mons added
Antoniadi added
Aonia Mons added
Aonia Planum added
Aonia Terra added
Aonia Tholus added
Aonium Sinus added
Apia added with exception
Apodis Catena added with exception
Apollinaris Mons added
Apollinaris Patera added
Apollinaris Sulci added
Apollinaris Tholus added
Apollo Patera added
Apsus Vallis added
Apt added
Arabia added
Arabia Terra added
Arago added
Aram Chaos added
Aram Dorsum added
Arandas added
Arcadia added
Arcadia Dorsa added
Arcadia Planitia added
Arda Valles added
Arena Colles added
Arena Dorsum added
Arena Rupes added
Ares Vallis added
Argas added with exception
Argentea Planum added
Argyre added
Argyre Cavi added
Argyre Mons added
Argyre Planitia added
Argyre Rupes added
Ariadnes Colles added
Arica added
Arima added
Arimanes Rupes added with exception
Arkhangelsky added
Arnon added
Arnus Vallis added
Aromatum Chaos added
Arrhenius added
Arsia Chasmata added
Arsia Mons added
Arsia Sulci added
Arsinoes Chaos added
Arta added
Artik added with exception
Artynia Catena added with exception
Asau added
Ascraeus Chasmata added
Ascraeus Mensa added
Ascraeus Mons added
Ascraeus Sulci added
Ascuris Planum added
Asimov added
Asopus Vallis added
Aspen added
Aspledon Undae added with exception
Astapus Colles added
Athabasca Valles added
Athena Patera added
Atlantis Chaos added
Atrax Dorsum added with exception
Atrax Fossa added with exception
Auce added with exception
Auki added with exception
Auqakuh Vallis added
Aureum Chaos added
Aurorae Chaos added
Aurorae Planum added
Aurorae Sinus added
Ausonia added
Ausonia Cavus added
Ausonia Mensa added
Ausonia Montes added
Australe Lingula added
Australe Mensa added
Australe Montes added
Australe Scopuli added
Australe Sulci added
Australis Patera added
Australis Tholus added
Auxo Dorsum added
Avan added with exception
Avarua added with exception
Aveiro added with exception
Avernus Cavi added with exception
Avernus Colles added with exception
Avernus Dorsa added with exception
Avernus Rupes added with exception
Avire added
Axius Valles added
Ayacucho added with exception
Ayr added
Azul added
Azusa added
Babakin added
Bacht added with exception
Bacolor added
Bada added
Badwater added
Baetis Chaos added
Baetis Chasma added
Baetis Labes added
Baetis Mensa added
Bahn added
Bahram Vallis added
Bak added
Bakhuysen added
Balboa added with exception
Baldet added
Balta added
Baltia added
Baltisk added with exception
Balvicar added
Bam added
Bamba added
Bamberg added
Banff added
Banh added
Baphyras Catena added with exception
Bar added
Barabashov added
Barnard added
Baro added
Barsukov added
Bashkaus Valles added
Basin added
Bathys Planum added
Batoka added with exception
Batos added with exception
Baucau added with exception
Baum added
Baykonyr added with exception
Bazas added with exception
Becquerel added
Beer added
Beloha added
Beltra added with exception
Belyov added with exception
Belz added
Bend added
Bentham added with exception
Bentong added with exception
Bernard added
Berseba added with exception
Beruri added
Betio added
Bhor added with exception
Bianchini added
Biblis Patera added
Biblis Tholus added
Bigbee added
Bira added
Bise added with exception
Bison added with exception
Bjerknes added
Bland added
Bled added
Blitta added with exception
Blois added
Bluff added
Blunck added
Boeddicker added
Bogia added
Bogra added
Bok added
Bole added
Bombala added with exception
Bond added
Bonestell added
Boola added
Bopolu added
Bor added
Bordeaux added
Boreales Scopuli added
Boreosyrtis added
Boreum Cavus added
Boru added with exception
Bosporos Planum added
Bosporos Rupes added
Bouguer added
Boulia added with exception
Bozkir added with exception
Bradbury added
Brashear added
Brazos Valles added
Bree added
Bremerhaven added
Briault added
Bridgetown added with exception
Bristol added
Broach added
Bronkhorst added with exception
Brush added
Bulhar added with exception
Bunge added
Bunnik added with exception
Burroughs added
Burton added
Buta added
Butte added
Buvinda Vallis added
Byala added with exception
Byrd added
Byske added with exception
Cadiz added
Cairns added
Calahorra added
Calamar added with exception
Calbe added with exception
Calydon Fossa added
Camargo added
Camichel added
Camiling added with exception
Camiri added with exception
Campbell added
Campos added
Can added
Canala added with exception
Canas added
Canaveral added
Canberra added
Candor added
Candor Chaos added
Candor Chasma added
Candor Colles added
Candor Labes added
Candor Mensa added
Candor Sulci added
Cangwu added with exception
Canillo added with exception
Cankuzo added
Canso added with exception
Cantoura added
Capen added
Capri Chasma added
Capri Mensa added
Caralis Chaos added
Cardona added
Cartago added
Casius added
Cassini added
Castril added
Catota added with exception
Cave added
Cavi Angusti added
Cavi Frigores added with exception
Cavi Novi added
Caxias added with exception
Cayon added with exception
Cebrenia added
Cecropia added
Cefalu added with exception
Centauri Montes added
Ceraunius added
Ceraunius Catena added
Ceraunius Fossae added
Ceraunius Tholus added
Cerberus added
Cerberus Dorsa added
Cerberus Fossae added
Cerberus Palus added
Cerberus Rupes added
Cerberus Tholi added
Cerulli added
Ceti Chasma added
Ceti Labes added
Ceti Mensa added
Chafe added with exception
Chalce added
Chalce Fossa added with exception
Chalce Montes added
Chalcoporos Rupes added
Chaman added with exception
Chamberlin added
Changsong added with exception
Chapais added
Charis Dorsum added
Charitum Montes added
Charitum Tholus added
Charleston added
Charlier added
Charlieu added with exception
Charybdis Scopulus added
Chasma Australe added
Chasma Boreale added
Chatturat added with exception
Chauk added with exception
Cheb added with exception
Chefu added with exception
Chekalin added
Chersonesus added
Chia added
Chico Valles added
Chimbote added with exception
Chincoteague added with exception
Chinju added with exception
Chinook added
Chive added with exception
Choctaw added with exception
Chom added with exception
Choyr added
Chronius Mons added
Chrysas Mensa added with exception
Chryse added
Chryse Chaos added
Chryse Colles added
Chryse Planitia added
Chrysokeras added
Chupadero added
Chur added
Cilaos added with exception
Circle added
Clanis Valles added with exception
Claritas added
Claritas Fossae added
Claritas Rupes added
Clark added
Clasia Vallis added
Cleia Dorsum added
Clogh added with exception
Clota Vallis added
Clova added with exception
Cluny added with exception
Cobalt added
Coblentz added
Cobres added with exception
Coimbra added
Colles Nili added
Coloe Fossae added
Colon added
Columbia Valles added
Columbus added
Comas Sola added
Conches added with exception
Concord added
Coogoon Valles added
Cooma added
Copais Palus added
Copernicus added
Coprates added
Coprates Catena added

Coprates Chasma added
Coprates Labes added
Coprates Mensa added
Coprates Montes added
Coracis Fossae added
Corby added
Corinto added
Coronae Montes added
Coronae Planum added
Coronae Scopulus added
Corozal added
Cost added
Cray added
Creel added
Crewe added
Crivitz added with exception
Crommelin added
Cross added
Crotone added
Cruls added
Cruz added
Cue added
Culter added with exception
Curie added
Cusus Valles added
Cyane Catena added
Cyane Fossae added
Cyane Sulci added with exception
Cyclopia added
Cydnus Rupes added with exception
Cydonia added
Cydonia Colles added
Cydonia Labyrinthus added
Cydonia Mensae added
Cypress added with exception
Daan added with exception
Daedalia Planum added
Daet added with exception
Daga Vallis added
Dalu Cavus added with exception
Daly added
Dana added
Danielson added
Dank added
Dao Vallis added
Darvel added
Darwin added
Davies added
Da Vinci added
Dawes added
Deba added
Degana added
Dein added
Dejnev added
Delta added
Deltoton Sinus added
Denning added
Depressio Hellespontica added
Dersu added with exception
Dese added with exception
Deseado added
Dessau added with exception
Deucalionis Regio added
Deuteronilus added
Deuteronilus Colles added
Deuteronilus Mensae added
de Vaucouleurs added
Deva Valles added with exception
Deva Vallis added
Dia Cau added
Diacria added
Diacria Patera added
Dilly added
Dingo added
Dinorwic added with exception
Dionysus Patera added
Dioscuria added
Dison added
Dittaino Valles added
Dixie added
Doanus Vallis added
Doba added
Dogana added with exception
Dokka added
Dokuchaev added
Dollfus added
Domoni added
Doon added with exception
Dorsa Argentea added
Dorsa Brevia added
Douglass added
Dowa added with exception
Downe added
Drava Valles added
Drilon Vallis added
Drinus Valles added with exception
Dromore added with exception
Dubis Vallis added
Dubki added with exception
Dukhan added
Dulce Vallis added
Dulovo added
Du Martheray added
Dunhuang added
Dunkassa added with exception
Durius Valles added
Dush added with exception
Du Toit added
Dzeng added with exception
Dzigai Vallis added
Eads added
Eagle added
Eberswalde added
Echt added
Echus Chaos added
Echus Chasma added
Echus Fossae added
Echus Montes added
Echus Palus added
Edam added
Eddie added
Eden Patera added
Edom added
Eger added with exception
Ehden added with exception
Eil added
Eilat added with exception
Ejriksson added
Elath added
Elaver Vallis added
Electris added
Electris Mons added
Elim added with exception
Ellsley added with exception
Elorza added
Ely added
Elysium added
Elysium Catena added
Elysium Chasma added
Elysium Fossae added
Elysium Mons added
Elysium Planitia added
Elysium Rupes added
E  Mareotis Tholus added
Endeavour added
Enipeus Vallis added
Eos Chaos added
Eos Chasma added
Eos Mensa added
Erebus Montes added
Eridania added
Eridania Mons added
Eridania Planitia added
Eridania Scopulus added
Erythraea Fossa added
Erythraeum Chaos added
Erythraeum Planum added
Escalante added
Escorial added
Esira added with exception
Esk added
Espino added with exception
Eudoxus added
Eumenides Dorsum added
Eunostos added
Euphrates added
Euphrates Patera added
Euripus Mons added
Evpatoriya added
Evros Vallis added
Faith added
Falun added with exception
Fancy added
Faqu added with exception
Farah Vallis added
Farim added
Fastov added with exception
Felis Dorsa added
Fenagh added with exception
Fesenkov added
Firsoff added
Fitzroy added
Flammarion added
Flat added
Flateyri added with exception
Flaugergues added
Floq added
Flora added
Focas added
Fontana added
Foros added with exception
Fortuna Fossae added
Fournier added
Freedom added
Frento Vallis added
Frigoris Scopulus added with exception
Funchal added with exception
Gaan added with exception
Gagra added with exception
Gah added
Galap added
Galaxias Chaos added
Galaxias Colles added
Galaxias Fluctus added with exception
Galaxias Fossae added
Galaxias Mensae added
Galaxius Mons added with exception
Galdakao added
Gale added
Gali added
Galilaei added
Galle added
Galu added
Gamboa added
Gan added
Gander added
Gandu added with exception
Gandzani added with exception
Ganges Catena added
Ganges Cavus added
Ganges Chaos added
Ganges Chasma added
Ganges Mensa added
Gardo added with exception
Gari added with exception
Garm added
Garni added
Gasa added
Gastre added with exception
Gatico added with exception
Gediz Vallis added
Gehon added
Gemina Lingula added
Gemini Scopuli added
Geryon Montes added
Gigas Fossae added
Gigas Sulci added
Gilbert added
Gill added
Glazov added
Gledhill added
Glendore added with exception
Glide added
Globe added
Goba added
Goff added
Gokwe added with exception
Gol added
Gold added
Golden added
Goldstone added
Gonnus Mons added with exception
Gordii Dorsum added
Gordii Fossae added
Gorgonum Chaos added
Gori added
Graff added
Granicus Valles added
Gratteri added
Greeley added
Green added
Greg added
Grindavik added
Gringauz added
Grjota Valles added
Grojec added
Groves added
Guaymas added
Guir added with exception
Gulch added
Gunjur added
Gunnison added
Gusev added
Gwash added with exception
Hadley added
Hadriaca Patera added
Hadriacus Cavi added
Hadriacus Mons added
Hadriacus Palus added
Halba added with exception
Haldane added
Hale added
Halex Fossae added
Halley added
Ham added
Hamaguir added with exception
Hamelin added
Handlova added with exception
Harad added with exception
Hargraves added
Harmakhis Vallis added
Harris added
Hartwig added
Hashir added
Havel Vallis added
Heaviside added
Hebes Chasma added
Hebes Mensa added
Hebrus Valles added
Hecates Tholus added
Hegemone Dorsum added with exception
Heimdal added
Heinlein added
Hellas added
Hellas Chaos added
Hellas Chasma added
Hellas Montes added
Hellas Planitia added
Hellespontus added
Hellespontus Montes added
Helmholtz added
Henbury added
Henry added
Henry Moore added
Hephaestus Fossae added
Hephaestus Rupes added
Hera Patera added
Herculaneum added
Her Desher Vallis added
Hermes Patera added
Hermus Vallis added
Herschel added
Hesperia added
Hesperia Dorsa added
Hesperia Planum added
Hibes Montes added
Hiddekel added
Hiddekel Cavus added with exception
Hiddekel Rupes added with exception
Hilo added
Himera Valles added
Hipparchus added
Hit added
Holden added
Holmes added
Honda added
Hooke added
Hope added
Horarum Mons added with exception
Horowitz added
Houston added
Hrad Vallis added
Hsuanch eng added with exception
Huallaga Vallis added
Huancayo added with exception
Huggins added
Hunten added
Huo Hsing Vallis added
Hussey added
Hutton added
Huxley added
Huygens added
Hyblaeus Catena added with exception
Hyblaeus Chasma added
Hyblaeus Dorsa added
Hyblaeus Fossae added
Hydaspis Chaos added
Hydrae Cavus added with exception
Hydrae Chaos added
Hydrae Chasma added
Hydraotes Chaos added
Hydraotes Colles added
Hypanis Valles added
Hyperboreae Undae added
Hyperborea Lingula added
Hyperborei Cavi added
Hyperboreus Labyrinthus added
Hyperboreus  Lacus  added
Hyperboreus Scopulus added with exception
Hypernotius Scopulus added with exception
Hypsas Vallis added
Iamuna Chaos added
Iamuna Dorsa added with exception
Iani Chaos added
Iapygia  Iapigia  added with exception
Iaxartes Tholus added
Iazu added
Iberus Vallis added
Ibragimov added
Icaria added
Icaria Fossae added
Icaria Planum added
Icaria Rupes added
Idaeus Fossae added
Igal added
II Thyle I added
Ikej added with exception
Imgr added with exception
Indus Vallis added
Innsbruck added
Ins added
Inta added
Inuvik added
Irbit added with exception
Irharen added with exception
Isara Valles added
Isidis Dorsa added
Isidis Planitia added
Isidis Regio added
Isil added
Ismeniae Fossae added
Ismenia Patera added
Ismenius Cavus added
Ismenius Lacus added
Issedon Paterae added
Issedon Tholus added
Ister Chaos added
Istok added
Ituxi Vallis added
Ius Chasma added
Ius Labes added
Ius Mensa added
Izendy added with exception
Jal added
Jama added with exception
Jampur added with exception
Jamuna added
Janssen added
Jarry Desloges added
Jeans added
Jeki added with exception
Jen added
Jezero added
Jezza added with exception
Jijiga added with exception
Jodrell added
Johannesburg added
Johnstown added
Jojutla added
Joly added
Jones added
Jorn added
Jovis Fossae added

Jovis Tholus added
Jumla added
Juventae Cavi added
Juventae Chasma added
Juventae Dorsa added
Juventae Fons added
Juventae Mensa added
Kachug added with exception
Kagoshima added
Kagul added with exception
Kaid added with exception
Kaiser added
Kaj added
Kakori added with exception
Kalba added
Kaliningrad added
Kalocsa added with exception
Kamativi added with exception
Kamloops added
Kamnik added with exception
Kampot added with exception
Kanab added with exception
Kandi added
Kankossa added with exception
Kansk added
Kantang added
Karpinsk added with exception
Karshi added
Kartabo added with exception
Karun Valles added
Karzok added with exception
Kasabi added with exception
Kasei Valles added
Kashira added
Kasimov added
Kasra added with exception
Katoomba added
Kaup added with exception
Kaw added
Kayne added with exception
Keeler added
Kem  added
Kepler added
Keren added with exception
Keul  added with exception
Khanpur added with exception
Kholm added with exception
Khurli added with exception
Kibuye added
Kifri added with exception
Kimry added with exception
Kin added
Kinda added
Kingston added
Kinkora added with exception
Kipini added
Kirs added
Kirsanov added with exception
Kisambo added with exception
Kison Tholus added
Kita added
Knobel added
Koga added
Kok added
Kolonga added
Kong added
Kontum added with exception
Korolev added
Korph added with exception
Koshoba added with exception
Kotido added with exception
Kotka added
Kourou added
Koval sky added
Koy added
Krasnoye added with exception
Kribi added with exception
Krishtofovich added with exception
Krupac added with exception
Kuba added with exception
Kufra added
Kuiper added
Kular added with exception
Kumak added with exception
Kumara added
Kunes added with exception
Kunowsky added
Kushva added with exception
Labeatis Catenae added
Labeatis Fossae added
Labeatis Fossae added
Labeatis Mensa added
Labeatis Mons added
Labou Vallis added
Labria added with exception
Lachute added with exception
Ladon Valles added
Laestrygon  Laestrigon  added with exception
Laf added
Lagarto added with exception
Lamas added
Lambert added
Lamont added
Lampland added
Land added
Langtang added with exception
La Paz added
Lapri added with exception
Lar added
Lassell added
Lasswitz added
Lau added
Layla added with exception
Layl Cavus added with exception
Lebu added with exception
Lederberg added
Leighton added
Leleque added with exception
Lemgo added with exception
Lemuria added
Lenya added with exception
Lethe Vallis added
Leuk added with exception
Le Verrier added
Lexington added
Liais added
Liberta added
Libertad added
Libya added
Libya Montes added
Licus Vallis added
Li Fan added
Linpu added with exception
Lins added
Lipany added with exception
Lipik added with exception
Liris Valles added
Lisboa added
Lismore added
Littleton added
Liu Hsin added
Livny added with exception
Llanesco added with exception
Lobo Vallis added
Locana added with exception
Lockyer added
Locras Valles added
Lod added
Lodwar added
Lohse added
Loire Valles added
Loja added with exception
Lomela added with exception
Lomonosov added
Lonar added
Longa added with exception
Loon added
Lopez added
Lorica added
Los added
Lota added with exception
Loto added
Louros Valles added
Louth added
Lowbury added with exception
Lowell added
Luba added
Lucaya added
Luck added
Lucus Planum added
Luga added with exception
Luki added with exception
Lunae Mensa added
Lunae Palus added
Lunae Planum added
Luqa added
Lutsk added with exception
Luzin added
Lycus Sulci added
Lydda added with exception
Lyell added
Lyot added
Ma adim Vallis added
Madler added
Madrid added
Mad Vallis added
Mafra added
Magadi added
Magelhaens added
Maggini added
Mago added
Magong added with exception
Maidstone added with exception
Main added
Maja Valles added
Majuro added
Makhambet added with exception
Malam Cavus added with exception
Malea Patera added
Malea Planum added
Mambali added with exception
Mamers Valles added
Manah added with exception
Mandora added with exception
Mangala Fossa added
Mangala Valles added
Manti added
Manzi added
Maraldi added
Marbach added with exception
Marca added with exception
Mare Acidalium added
Mare Australe added
Mare Boreum added
Mare Chronium added
Mare Cimmerium added
Mare Erythraeum added
Mare Hadriacum added
Mareotis Fossae added
Mare Serpentis added
Mare Sirenum added
Mare Tyrrhenum added
Margaritifer Chaos added
Margaritifer Sinus added
Margaritifer Terra added
Mari added
Maricourt added
Marikh Vallis added
Mariner added
Marte Vallis added
Marth added
Martin added
Martynov added
Martz added
Masursky added
Matara added
Matrona Vallis added
Maumee Valles added
Maunder added
Mawrth Vallis added
Mazamba added
McLaughlin added
McMurdo added
Medrissa added with exception
Medusae Fossae added
Medusae Sulci added
Mega added
Meget added with exception
Melas Chasma added
Melas Dorsa added
Melas Fossae added
Melas Labes added
Melas Mensa added
Mellish added
Mellit added with exception
Memnonia added
Memnonia Fossae added
Memnonia Sulci added
Mena added
Mendel added
Mendota added with exception
Meridiani Planum added
Meroe added
Meroe Patera added
Micoud added
Mie added
Mila added with exception
Milankovic added
Milford added
Millman added
Millochau added
Milna added
Minio Vallis added
Mirtos added with exception
Misk added with exception
Mistretta added with exception
Mitchel added
Miyamoto added
Mliba added with exception
Moab added
Moanda added
Moa Valles added
Moeris Lacus added
Mohawk added
Mojave added
Molesworth added
Moni added
Montevallo added
Morava Valles added
Morella added
Moreux added
Moroz added
Morpheos Rupes added with exception
Mosa Vallis added
Moss added
Muara added with exception
Muller added
Munda Vallis added
Murgoo added
Murray added
Musmar added with exception
Mut added
Mutch added
Naar added
Naic added
Nain added
Naju added with exception
Naktong Vallis added
Nakusp added with exception
Nan added
Nanedi Valles added
Nansen added
Napo Vallis added
Nardo added with exception
Naro Vallis added
Naruko added
Naryn added
Nat Cavus added
Naukan added with exception
Navan added
Navua Valles added
Nazca added
Nectar added
Nectaris Fossae added
Nectaris Montes added
Negele added
Negril added with exception
Neith Regio added
Neive added with exception
Nema added with exception
Nepa added
Nepenthes added
Nepenthes Mensae added
Nepenthes Patera added
Nepenthes Planum added
Nereidum Fretum added
Nereidum Montes added
Nestus Valles added
Neukum added
Never added with exception
Neves added
New Bern added
Newcomb added
New Haven added
New Plymouth added
Newport added
Newton added
Nhill added with exception
Nia Chaos added
Nia Fossae added
Nia Mensa added
Nia Tholus added
Nia Vallis added
Nicer Vallis added
Nicholson added
Nier added
Niesten added
Nif added
Niger Vallis added
Niliacus Lacus added
Nili Fossae added
Nili Patera added
Nili Tholus added
Nilokeras added
Nilokeras Fossa added
Nilokeras Mensae added
Nilokeras Scopulus added with exception
Nilosyrtis added
Nilosyrtis Mensae added
Nilus Chaos added
Nilus Dorsa added
Nilus Mensae added
Nipigon added
Niquero added
Nirgal Vallis added
Nitro added
Nix Olympica added
Njesko added with exception
N  Mareotis Tholus added
Noachis added
Noachis Terra added
Noc Cavus added with exception
Noctis Fossae added
Noctis Labyrinthus added
Noctis Tholus added
Noma added
Noord added with exception
Nordenskiold added
Northport added
Novara added
Nqutu added with exception
Nune added with exception
Nutak added with exception
Nybyen added with exception
Obock added
Ocampo added
Oceanidum Fossa added
Oceanidum Mons added
Ochakov added with exception
Ochus Valles added
Octantis Cavi added
Octantis Mons added
Oenotria Plana added
Oenotria Scopuli added with exception
Oenotria Scopulus added
Oglala added with exception
Ogygis Regio added
Ogygis Rupes added
Ogygis Undae added
Ohara added
Okavango Valles added
Okhotsk added with exception
Okotoks added
Olenek added with exception
Olom added
Oltis Valles added
Olympia added
Olympia Cavi added
Olympia Mensae added
Olympia Planitia added
Olympia Planum added
Olympia Rupes added
Olympia Undae added
Olympica Fossae added
Olympus Mons added
Olympus Paterae added

Olympus Rupes added
Ome added
Omura added
Onon added
Oodnadatta added with exception
Ophir added
Ophir Catenae added
Ophir Cavus added
Ophir Chasma added
Ophir Labes added
Ophir Mensa added
Ophir Planum added
Oraibi added
Orcus Patera added
Ore added
Orinda added
Orson Welles added
Ortygia added
Ortygia Colles added with exception
Ortygia Tholus added
Ostrov added
Osuga Valles added
Oti Fossae added
Ottumwa added with exception
Oudemans added
Oxia Chaos added
Oxia Colles added
Oxia Palus added
Oxus added
Oxus Cavus added
Oxus Patera added
Oyama added
Pabo added
Padus Vallis added
Pai added
Paks added with exception
Pal added
Palana added with exception
Palikir added
Pallacopas Vallis added
Palos added
Panchaia added
Panchaia Rupes added
Pandorae Fretum added
Pangboche added
Parana Valles added
Paros added
Parva Planum added
Pasithea Dorsum added
Pasteur added
Patapsco Vallis added
Pau added
Pavonis Chasma added
Pavonis Fossae added
Pavonis Mons added
Pavonis Sulci added
Peace Vallis added
Pebas added with exception
Peixe added with exception
Peneus Mons added
Peneus Palus added
Peneus Patera added
Penticton added
Peraea Cavus added
Peraea Mons added
Perepelkin added
Peridier added
Perrotin added
Persbo added with exception
Peta added
Pettit added
Phaenna Dorsum added with exception
Phaethontis added
Phedra added with exception
Philadelphia added
Phillips added
Phison added
Phison Rupes added
Phlegethon Catena added
Phlegra added
Phlegra Dorsa added
Phlegra Montes added
Phoenicis Lacus added
Phon added with exception
Phrixi Regio added
Phrixi Rupes added
Pica added
Pickering added
Pina added
Pindus Mons added with exception
Pinglo added with exception
Pital added with exception
Pityusa Dorsa added
Pityusa Patera added
Pityusa Rupes added
Piyi added with exception
Planum Angustum added
Planum Australe added
Planum Boreum added
Planum Chronium added
Platte added
Playfair added
Plum added
Podor added with exception
Pollack added
Polotsk added
Pompeii added
Poona added
Port Au Prince added
Porter added
Porth added with exception
Portsmouth added
Porvoo added with exception
Poti added
Poynting added
Prao added
Priestley added
Princeton added
Proctor added
Promethei Chasma added
Promethei Lingula added
Promethei Mons added
Promethei Planum added
Promethei Rupes added
Promethei Sinus added
Promethei Terra added
Propontis added
Protei Regio added
Protonilus added
Protonilus Mensae added
Protva Valles added
Ptolemaeus added
Pulawy added with exception
Punsk added
Pursat added
Puyo added with exception
Pylos added with exception
Pyramus Fossae added
Pyrrhae Chaos added
Pyrrhae Fossae added
Pyrrhae Regio added
Qiba added with exception
Quenisset added
Quick added with exception
Quines added with exception
Quorn added
Quthing added with exception
Rabe added
Radau added
Raga added
Rahe added
Rahway Valles added
Rakke added with exception
Rana added
Raub added
Rauch added
Rauna added
Ravius Valles added with exception
Ravi Vallis added
Rayadurg added
Rayleigh added
Redi added
Renaudot added
Rengo added with exception
Resen added
Reull Vallis added
Reutov added with exception
Reuyl added with exception
Revda added
Reykholt added
Reynolds added
Rhabon Valles added with exception
Ribe added
Richardson added
Rimac added with exception
Rincon added
Ritchey added
Robert Sharp added
Roddenberry added
Roddy added
Romny added with exception
Rong added
Rongxar added with exception
Roseau added
Ross added
Rossby added
Rubicon Valles added with exception
Ruby added
Rudaux added
Ruhea added with exception
Runanga added
Runa Vallis added
Rupes Tenuis added
Russell added
Rutherford added
Ruza added with exception
Rynok added with exception
Rypin added with exception
Sabis Vallis added
Sabo added
Sabrina Vallis added
Sacra Dorsa added
Sacra Fossae added
Sacra Mensa added
Sacra Sulci added with exception
Sagan added
Saheki added
Salaga added with exception
Samara Valles added
Sandila added with exception
Sangar added
San Juan added
Santaca added with exception
Santa Cruz added
Santa Fe added
Saravan added with exception
Sarh added with exception
Sarn added with exception
Sarno added with exception
Satka added
Sauk added with exception
Savannah added
Savich added
Say added with exception
Scamander Vallis added
Scandia added
Scandia Cavi added
Scandia Colles added
Scandia Tholi added
Schaeberle added
Schiaparelli added
Schmidt added
Schoner added
Schroeter added
Scylla Scopulus added with exception
Sebec added
Secchi added
Sefadu added
Selevac added with exception
Semeykin added
Seminole added
Senus Vallis added
Sepik Vallis added
Sevel added with exception
Sevi added with exception
Sfax added with exception
Shalbatana Vallis added
Shambe added
Shardi added with exception
Sharonov added
Shatskiy added with exception
Shawnee added
Sian added
Sibiti added with exception
Sibu added with exception
Sibut added
Sigli added
Silinka Vallis added
Siloe Patera added
Simois Colles added
Simud Valles added
Sinai added
Sinai Dorsa added
Sinai Fossae added
Sinai Planum added
Sinda added
Singa added with exception
Sinop added with exception
Sinton added
Sinus Meridiani added
Sinus Sabaeus added
Sirenum Fossae added
Sirenum Mons added
Sirenum Tholus added
Sisyphi Cavi added
Sisyphi Montes added
Sisyphi Planum added
Sisyphi Tholus added
Sithonius Lacus added
Sitka added with exception
Siton Undae added
Sitrah added with exception
Sklodowska added
Slipher added
Smith added
Soffen added
Sogel added
Sokol added
Solano added with exception
Solis Dorsa added
Solis Lacus added
Solis Planum added
Somerset added
Soochow added with exception
Souris added
South added
Spallanzani added
Spry added
Spur added
Sripur added with exception
Stege added
Steinheim added
Steno added
Stobs added with exception
Stokes added
Ston added
Stoney added
Stura Vallis added
Stygis Catena added
Stygis Fossae added
Styx added
Styx Dorsum added with exception
Suata added with exception
Subur Vallis added
Sucre added with exception
Suess added
Suf added
Sulak added
Sulci Gordii added
Sumgin added
Sungari Vallis added
Surinda Valles added with exception
Surius Vallis added
Surt added with exception
Suzhi added
Swanage added with exception
Syria added
Syria Colles added
Syria Mons added
Syria Planum added
Syrtis Major added
Syrtis Major Planitia added
Syrtis Major Planum added
Sytinskaya added
Tabor added
Tabou added with exception
Tader Valles added
Taejin added with exception
Tagus Valles added
Tak added
Tala added
Talas added
Talsi added with exception
Taltal added with exception
Talu added
Tame added
Tanaica Montes added
Tanais added
Tanais Fossae added
Tana Vallis added
Tantalus Fluctus added with exception
Tantalus Fossae added
Tara added
Tarakan added with exception
Tarata added with exception
Tarma added
Tarq added with exception
Tarrafal added with exception
Tarsus added
Tartarus Colles added
Tartarus Montes added
Tartarus Rupes added
Tartarus Scopulus added
Taus Vallis added
Tavua added with exception
Taxco added with exception
Taytay added
Taza added with exception
Tecolote added with exception
Teisserenc de Bort added
Tejn added with exception
Telz added
Tem  added
Tempe added
Tempe Colles added
Tempe Fossae added
Tempe Mensa added
Tempe Terra added
Tenuis Cavus added
Tenuis Mensa added
Tepko added with exception
Terby added
Termes Vallis added
Terra Cimmeria added
Terra Meridiani added
Terra Sabaea added
Terra Sirenum added
Teviot Vallis added
Tharsis added
Tharsis Montes added
Tharsis Tholus added
Thaumasia added
Thaumasia Fossae added
Thaumasia Planum added
Thermia added with exception
Thila added
Thira added
Thom added
Thoth added
Thule added
Thyles Chasma added
Thyles Montes added
Thyles Rupes added
Thymiamata added
Tibrikot added
Tignish added with exception
Tigre Valles added
Tikhonravov added
Tikhov added
Tile added
Timaru added with exception
Timbuktu added with exception
Timoshenko added
Tinia Valles added
Tinjar Valles added
Tinto Vallis added
Tisia Valles added
Tithoniae Catena added with exception
Tithoniae Catenae added with exception
Tithoniae Fossae added with exception
Tithoniae Fossae added with exception
Tithonium Chasma added
Tithonius Lacus added
Tiu Valles added
Tivat added
Tivoli added with exception

Tiwi added with exception
Toconao added
Tokko added with exception
Tokma added with exception
Tolon added with exception
Tomari added with exception
Tombaugh added
Tombe added
Tomini added
Tono added
Tooting added
Torbay added with exception
Toro added
Torso added
Torup added with exception
Tractus Albus added
Tractus Catena added
Tractus Fossae added
Trebia Valles added with exception
Trinacria added
Trinidad added
Triolet added
Trivium Charontis added
Troika added with exception
Trouvelot added
Troy added
Trud added
Trumpler added
Tsau added with exception
Tsukuba added
Tuapi added with exception
Tugaske added with exception
Tumul added with exception
Tungla added
Tura added
Turbi added with exception
Turma added with exception
Tuscaloosa added
Tuskegee added
Tycho Brahe added
Tyndall added
Tyras Vallis added
Tyrrhena Dorsa added
Tyrrhena Fossae added
Tyrrhena Mons added
Tyrrhena Patera added
Tyrrhena Terra added
Tyrrhenus Labyrinthus added
Tyrrhenus Mons added
Tyuratam added with exception
Ubud added with exception
Uchronia added with exception
Udzha added with exception
Ultima Lingula added
Ultimi Cavi added
Ultimi Scopuli added
Ultimum Chasma added
Ulu added
Ulya added
Ulysses Colles added
Ulysses Fossae added
Ulysses Patera added
Ulysses Tholus added
Ulyxis Rupes added
Umatac added with exception
Umbra added
Uranius Dorsum added
Uranius Fossae added
Uranius Mons added
Uranius Patera added
Uranius Tholus added
Urk added
Usiku Cavus added with exception
Utan added with exception
Utopia added
Utopia Planitia added
Utopia Rupes added
Uzboi Vallis added
Uzer added
Vaals added
Vaduz added
Valga added
Valles Marineris added
Valverde added
Varus Valles added with exception
Vastitas Borealis added
Vato added with exception
Vaux added with exception
Vedra Valles added
Verde Vallis added
Verlaine added
Vernal added
Very added
Viana added with exception
Vichada Valles added
Victoria added
Vik added
Vils added with exception
Vinogradov added
Vinogradsky added
Virrat added with exception
Vishniac added
Vistula Valles added with exception
Vivero added with exception
Voeykov added with exception
Vogel added
Volgograd added
Vol sk added
Von Karman added
Voo added
Voza added with exception
Vulcani Pelagus added
Wabash added
Wafra added with exception
Wahoo added
Waikato Vallis added
Wajir added with exception
Wallace added
Walla Walla Vallis added
Wallops added
Wallula added
Warra added with exception
Warrego Valles added
Waspam added
Wassamu added with exception
Wau added with exception
Weert added
Wegener added
Weinbaum added
Wells added
Wer added
Wicklow added with exception
Wien added
Williams added
Wilmington added
Wiltz added
Windfall added
Wink added
Winslow added
Wirtz added
Wislicenus added
W  Mareotis Tholus added
Woking added
Woolgar added with exception
Woomera added
Worcester added
Wright added
Wukari added with exception
Wum added
Wynn Williams added
Xainza added with exception
Xanthe added
Xanthe Chaos added
Xanthe Dorsa added
Xanthe Montes added
Xanthe Scopulus added
Xanthe Terra added
Xui added
Yakima added
Yala added with exception
Yalata added with exception
Yalgoo added
Yaonis Regio added
Yar added
Yaren added with exception
Yat added
Yebra added with exception
Yegros added with exception
Yellowknife added
Yorktown added
Yoro added with exception
Yungay added
Yuty added
Zarand added with exception
Zaranj added with exception
Zarqa Valles added
Zea Dorsa added
Zephyria added
Zephyria Fluctus added with exception
Zephyria Mensae added
Zephyria Planum added
Zephyria Tholus added
Zephyrus Fossae added
Zeus Patera added
Zhigou added with exception
Zilair added with exception
Zir added
Zongo added with exception
Zulanka added with exception
Zumba added
Zuni added
Zunil added
Zutphen added

In [139]:
landing_site=[]
for i in attr_feature['Clean_Feature_Name']:
    q = ads.SearchQuery(q=i, keyword='landing site mars', fl=['bibcode'], rows=1)
    bibcodes = [j.bibcode for j in q]
    metrics_query=ads.MetricsQuery(bibcodes)
    try:
        metrics_response = metrics_query.execute()
        landing_site.append(1)
        print(i + " landing site added")
    except:
        landing_site.append(0)
        print(i + " no landing site added")

In [140]:
attr_feature['landing site'] = landing_site

In [141]:
attr_feature['polygon'] = polygon

In [133]:
attr_feature['number of papers'] = np_sum
attr_feature['number of citing papers'] = ncp_sum
attr_feature['number of self-citations'] = nsc_sum
attr_feature['total number of citations'] = tnc_sum
attr_feature['total number of refereed citations'] = tnrc_sum
attr_feature['query date'] = query_date

In [142]:
attr_feature

,Feature_ID,Clean_Feature_Name,Target,Diameter,Center_Latitude,Center_Longitude,Northern_Latitude,Southern_Latitude,Eastern_Longitude,Western_Longitude,...,Reference,Origin,number of papers,number of citing papers,number of self-citations,total number of citations,total number of refereed citations,query date,landing site,polygon
0,4,Abalos Colles,Mars,235.83,76.83,-71.65,78.78,74.81,-66.61,-75.46,...,57.0,"Named for classical albedo feature at 72N, 70W.",4,144,1,144,123,05/12/2017,0,"[[[-68.42836570739746, 74.97826194763184], [-6..."
1,14147,Abalos Mensa,Mars,129.18,81.17,-75.60,82.40,80.21,-69.48,-80.66,...,57.0,Classical albedo feature name.,11,210,10,216,179,05/12/2017,0,"[[[-73.63830757141113, 80.26974678039551], [-7..."
2,14148,Abalos Scopuli,Mars,109.16,80.72,-76.56,81.96,80.20,-69.48,-80.53,...,57.0,Classical albedo feature name.,3,10,0,11,8,05/12/2017,0,"[[[-74.60061454772949, 80.95564079284668], [-7..."
3,5,Abalos Undae,Mars,442.74,78.52,-87.50,82.20,74.94,-76.97,-98.60,...,57.0,"Classical albedo feature at 72N, 70W.",6,49,1,49,38,05/12/2017,0,"[[[-80.35336875915527, 80.58683967590332], [-7..."
4,6,Aban,Mars,4.28,15.91,111.10,15.94,15.87,111.14,111.06,...,36.0,Town in Russia.,1,6,0,6,3,05/12/2017,0,"[[[111.101976394653, 15.8708324432373], [111.1..."
5,25,Abus Vallis,Mars,60.99,-5.49,-147.20,-5.02,-5.99,-147.16,-147.28,...,56.0,Classical name for Humber River in England.,5,8,0,8,6,05/12/2017,0,[]
6,31,Achar,Mars,5.36,45.43,123.16,45.48,45.39,123.23,123.10,...,36.0,Town in Uruguay.,1,4,0,4,3,05/12/2017,0,"[[[123.165567398071, 45.3864192962646], [123.1..."
7,34,Acheron Catena,Mars,421.77,37.47,-100.80,40.70,33.51,-98.29,-103.29,...,57.0,"Named for classical albedo feature at 35N, 140W.",8,115,2,119,93,05/12/2017,0,[]
8,35,Acheron Fossae,Mars,703.11,38.27,-135.02,40.03,31.47,-129.08,-143.10,...,57.0,"From classical albedo feature at 35N, 140W.",63,1883,92,2594,2189,05/12/2017,0,"[[[-129.68730354309082, 37.86834907531738], [-..."
9,36,Acidalia Colles,Mars,356.30,50.34,-23.09,52.96,48.42,-19.63,-28.23,...,71.0,From classical albedo feature name.,24,987,23,1219,1093,05/12/2017,0,"[[[-19.97706413269043, 51.070783615112305], [-..."
10,37,Acidalia Mensa,Mars,226.86,46.69,-25.34,48.69,45.03,-22.97,-28.19,...,71.0,From classical albedo feature name.,83,2315,272,3843,3234,05/12/2017,0,"[[[-23.437543869018555, 47.826555252075195], [..."
11,38,Acidalia Planitia,Mars,3362.97,49.76,-20.74,68.67,14.76,15.00,-55.00,...,57.0,"From classical albedo feature at 44N, 21W.",341,4774,1060,10080,8705,05/12/2017,1,"[[[1.239706039428711, 39.644025802612305], [0...."
12,14182,Ada,Mars,2.09,-3.06,-3.22,-3.04,-3.08,-3.21,-3.24,...,74.0,"Town in Oklahoma, USA.",78,2272,57,3049,2594,05/12/2017,0,"[[[-3.2239589691159836, -3.07810401916504], [-..."
13,45,Adamas Labyrinthus,Mars,853.00,35.70,105.12,41.07,30.34,111.46,96.27,...,57.0,"Classical albedo feature name; ""A River of Dia...",5,82,0,86,70,05/12/2017,0,"[[[105.58868598937988, 38.07891273498535], [10..."
14,46,Adams,Mars,90.22,30.91,163.10,31.68,30.15,163.99,162.22,...,68.0,Walter S.; American astronomer (1876-1956).,496,8333,2187,17668,15348,05/12/2017,1,"[[[163.118543624878, 30.1533336639404], [163.1..."
15,65,Aeolis,Mars,0.00,-4.94,145.00,-4.94,-4.94,145.00,145.00,...,60.0,Floating island where winds were kept in a cave.,2000,11498,9158,38994,33426,05/12/2017,1,[]
16,15019,Aeolis Dorsa,Mars,459.17,-5.05,152.63,-1.03,-8.13,156.42,148.60,...,71.0,Classical albedo feature name.,76,1285,123,1820,1557,05/12/2017,0,[]
17,66,Aeolis Mensae,Mars,785.09,-3.25,140.63,2.07,-6.56,146.95,135.33,...,57.0,Classical albedo feature name.,211,3876,838,7986,6643,05/12/2017,1,"[[[140.39999961853027, -0.733449935913086], [1..."
18,15000,Aeolis Mons,Mars,88.99,-5.08,137.85,-4.46,-5.61,138.62,137.11,...,71.0,Classical albedo feature name.,591,7328,2484,18192,15503,05/12/2017,1,[]
19,15001,Aeolis Palus,Mars,111.63,-4.47,137.42,-4.18,-5.39,138.65,136.75,...,71.0,Classical albedo feature name.,149,2307,236,3665,3078,05/12/2017,1,[]
20,14165,Aeolis Planum,Mars,852.81,-1.14,144.76,4.40,-6.68,149.98,139.08,...,71.0,Classical albedo feature name.,751,7257,3753,19952,17291,05/12/2017,1,"[[[145.30062675476074, 1.135274887084961], [14..."
21,15031,Aeolis Serpens,Mars,538.55,-1.38,149.57,2.48,-4.90,152.00,147.68,...,57.0,Classical albedo feature name.,375,6406,1406,14090,11904,05/12/2017,1,[]
22,68,Aeria,Mars,0.00,9.88,50.00,9.88,9.88,50.00,50.00,...,60.0,"Greek name for Egypt; ""far land of mist"".",25,88,6,124,114,05/12/2017,0,[]
23,69,Aesacus Dorsum,Mars,276.69,36.82,153.15,38.69,34.70,154.72,152.28,...,57.0,"From albedo feature at 45N, 205W.",0,0,0,0,0,05/12/2017,0,[]
24,71,Aetheria,Mars,0.00,39.67,130.00,39.67,39.67,130.00,130.00,...,60.0,Upper world; land of living.,15,67,1,68,60,05/12/2017,0,[]
25,72,Aethiopis,Mars,0.00,9.88,130.00,9.88,9.88,130.00,130.00,...,60.0,Countries of the Ethiopians on southern edge o...,11,24,0,27,23,05/12/2017,0,[]
26,79,Aganippe Fossa,Mars,537.16,-8.49,-126.00,-4.06,-12.85,-124.77,-126.86,...,57.0,Classical albedo feature name.,1,5,0,5,5,05/12/2017,0,[]
27,81,Agassiz,Mars,108.77,-69.88,-88.89,-68.97,-70.80,-86.20,-91.54,...,68.0,Jean L.; American naturalist (1807-1873).,14,337,4,351,317,05/12/2017,0,"[[[-88.81912803649902, -70.80104637146], [-88...."
28,114,Airy,Mars,43.05,-5.14,0.05,-4.77,-5.50,0.42,-0.31,...,68.0,George B.; British astronomer (1801-1892).,1964,15029,6003,38390,34560,05/12/2017,1,"[[[0.064416042621541, -5.500483014882271], [0...."
29,115,Airy 0,Mars,0.79,-5.07,0.00,-5.07,-5.08,0.01,-0.01,...,309.0,Small crater within crater Airy that defines z...,1576,14039,5047,34197,30855,05/12/2017,1,"[[[0.001520156860352, -5.080926895141602], [0...."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1866,6640,Yar,Mars,6.18,22.27,-39.15,22.32,22.22,-39.09,-39.20,...,36.0,Town in Russia.,3,59,0,59,52,05/12/2017,0,"[[[-39.147054672240984, 22.2179393768311], [-3..."
1867,14625,Yaren,Mars,9.19,-43.88,-137.45,-43.80,-43.96,-137.34,-137.55,...,36.0,Town in Nauru.,0,0,0,0,0,05/12/2017,0,"[[[-137.444883346558, -43.9588756561279], [-13..."
1868,6644,Yat,Mars,7.46,18.13,-29.03,18.19,18.07,-28.96,-29.09,...,36.0,Town in Niger.,2,89,0,89,88,05/12/2017,0,"[[[-29.026990890502987, 18.0670261383057], [-2..."
1869,6649,Yebra,Mars,4.85,20.79,105.69,20.83,20.75,105.73,105.64,...,36.0,Town in Spain.,0,0,0,0,0,05/12/2017,0,"[[[105.688375473022, 20.7498455047607], [105.6..."
1870,6650,Yegros,Mars,13.98,-22.30,-23.66,-22.18,-22.42,-23.54,-23.79,...,36.0,Town in Paraguay.,0,0,0,0,0,05/12/2017,0,"[[[-23.663908004761026, -22.4202499389648], [-..."
1871,15032,Yellowknife,Mars,0.12,-4.58,137.44,-4.58,-4.58,137.44,137.44,...,74.0,"Town in the Northwest Territories, Canada.",189,686,345,1422,1284,05/12/2017,0,[]
1872,6671,Yorktown,Mars,8.01,22.88,-48.65,22.95,22.81,-48.58,-48.72,...,36.0,American colonial town (Virginia).,16,212,7,237,200,05/12/2017,1,"[[[-48.65008354187, 22.8118762969971], [-48.65..."
1873,6672,Yoro,Mars,9.61,22.80,-28.04,22.88,22.72,-27.95,-28.13,...,36.0,Town in Honduras.,0,0,0,0,0,05/12/2017,0,"[[[-28.039140701294002, 22.7197284698486], [-2..."
1874,6681,Yungay,Mars,19.69,-43.87,-44.75,-43.70,-44.03,-44.52,-44.98,...,36.0,Town in Peru.,25,176,14,239,214,05/12/2017,0,"[[[-44.748991012573015, -44.0332221984863], [-..."
1875,6685,Yuty,Mars,19.06,22.16,-34.09,22.32,22.00,-33.92,-34.27,...,36.0,Town in Paraguay.,12,502,2,571,499,05/12/2017,0,"[[[-34.089700698852994, 21.9985866546631], [-3..."
1876,14212,Zarand,Mars,2.78,-3.41,-1.50,-3.39,-3.44,-1.47,-1.52,...,179.0,Town in Iran.,0,0,0,0,0,05/12/2017,0,"[[[-1.4967441558840164, -3.43516159057617], [-..."
1877,14337,Zaranj,Mars,27.41,12.09,113.05,12.32,11.86,113.29,112.82,...,36.0,Town in Afghanistan.,0,0,0,0,0,05/12/2017,0,"[[[113.060346603394, 11.8620738983154], [113.0..."
1878,14859,Zarqa Valles,Mars,21.37,0.32,80.59,3.93,-3.45,82.87,76.60,...,74.0,River in Jordan.,1,15,0,15,13,05/12/2017,0,[]
1879,6708,Zea Dorsa,Mars,249.02,-48.87,80.54,-47.11,-50.65,83.71,77.38,...,57.0,Classical albedo feature name.,1,9,0,9,9,05/12/2017,0,"[[[82.18731880187988, -50.52229881286621], [81..."
1880,6719,Zephyria,Mars,0.00,0.00,165.00,0.00,0.00,165.00,165.00,...,60.0,Land of the west wind.,51,820,46,954,821,05/12/2017,0,[]
1881,15195,Zephyria Fluctus,Mars,42.00,0.72,155.53,0.96,0.51,155.71,155.29,...,71.0,Classical albedo feature name.,0,0,0,0,0,05/12/2017,0,[]
1882,6720,Zephyria Mensae,Mars,333.61,-11.62,171.98,-8.84,-14.38,174.40,169.23,...,57.0,Albedo feature name.,13,279,11,291,221,05/12/2017,0,"[[[172.47260093688965, -8.836355209350586], [1..."
1883,14164,Zephyria Planum,Mars,575.11,-1.08,153.73,3.26,-5.42,156.75,149.96,...,71.0,Classical albedo feature name.,25,645,28,697,599,05/12/2017,0,"[[[156.00415229797363, -5.415916442871094], [1..."
1884,6721,Zephyria Tholus,Mars,35.95,-19.75,172.92,-19.44,-20.05,173.20,172.61,...,57.0,Albedo feature name.,10,438,5,465,426,05/12/2017,0,"[[[172.91116905212402, -19.470535278320312], [..."
1885,6722,Zephyrus Fossae,Mars,306.19,23.93,144.19,26.48,21.40,145.80,142.83,...,57.0,Albedo feature name.,3,1,0,2,2,05/12/2017,0,"[[[144.96639442443848, 26.35270118713379], [14..."
1886,15689,Zeus Patera,Mars,65.00,18.39,-132.93,18.91,17.80,-132.53,-133.51,...,174.0,"Greek sky, thunder and lightning god, who rule...",4,9,0,10,10,05/12/2017,0,[]
1887,6730,Zhigou,Mars,21.86,-29.10,-102.59,-28.96,-29.24,-102.38,-102.80,...,74.0,Town in China.,0,0,0,0,0,05/12/2017,0,"[[[-102.595331192017, -29.2429676055908], [-10..."
1888,6737,Zilair,Mars,46.91,-31.81,-32.94,-31.41,-32.21,-32.46,-33.40,...,36.0,Town in Russia.,0,0,0,0,0,05/12/2017,0,"[[[-32.92231559753401, -32.2054843902588], [-3..."
1889,6743,Zir,Mars,6.16,18.54,-36.54,18.60,18.49,-36.49,-36.60,...,36.0,Town in Turkey.,4,25,0,25,24,05/12/2017,0,"[[[-36.541563034058015, 18.4930324554443], [-3..."
1890,6750,Zongo,Mars,46.83,-33.76,-41.69,-33.36,-34.15,-41.21,-42.16,...,36.0,Town in Zaire.,0,0,0,0,0,05/12/2017,0,"[[[-41.677206039428995, -34.1509971618652], [-..."
1891,6946,Zulanka,Mars,43.12,-2.27,-42.16,-1.91,-2.63,-41.80,-42.52,...,36.0,Town in Russia.,0,0,0,0,0,05/12/2017,0,"[[[-42.15385246276901, -2.6348876953125], [-42..."
1892,6951,Zumba,Mars,2.93,-28.67,-133.07,-28.64,-28.69,-133.05,-133.10,...,179.0,Town in Ecuador.,8,93,3,115,95,05/12/2017,0,"[[[-133.073438644409, -28.693208694458], [-133..."
1893,6764,Zuni,Mars,24.28,19.22,-29.58,19.43,19.02,-29.36,-29.79,...,36.0,"Town in New Mexico, USA.",4,71,1,76,57,05/12/2017,0,"[[[-29.570692062377987, 19.0184535980225], [-2..."
1894,6765,Zunil,Mars,10.26,7.70,166.19,7.79,7.61,166.28,166.10,...,173.0,Mayan village in Guatemala.,61,1070,82,1471,1291,05/12/2017,0,"[[[166.192293167114, 7.61384010314941], [166.1..."
1895,6768,Zutphen,Mars,38.29,-13.85,174.32,-13.53,-14.18,174.65,173.99,...,36.0,Town in The Netherlands.,4,61,1,61,56,05/12/2017,0,"[[[174.326848983765, -14.1758460998535], [174...."

In [143]:
#Creating pandas dataframe to csv
attr_feature.to_csv("mars_gaz_stats", sep=',', header=True, index=False, encoding='utf-8')

In [145]:
attr_feature = attr_feature.drop('polygon', 1)

In [147]:
#Creating geojson
json_result_string = attr_feature.to_json(
    orient = 'records',
    double_precision=12,
    date_format='iso'
)

In [148]:
json_coord_string = polygon.to_json(
    orient = 'records',
    double_precision=12,
    date_format='iso'
)

In [149]:
json_result = json.loads(json_result_string)
json_coords = json.loads(json_coord_string)

In [150]:
geojson = {
    'type': 'FeatureCollection',
    'features': []
}

In [151]:
for poly, record in zip(json_coords, json_result):
    geojson['features'].append({
        'type': 'Feature',
        'geometry': {
            'type': 'Polygon',
            'coordinates': poly,
        },
        'properties': record,
    })

In [152]:
with open('mapdata.json', 'w', encoding = 'utf-8') as f:
    f.write(json.dumps(geojson, indent = 2, ensure_ascii=False))

In [ ]:
np7180 = [] #Number of Papers
ncp7180 = [] #number of citing papers
nsc7180 = [] #number of self citations
tnc7180 = [] #Total number of citations
tnrc7180 = [] #Total number of refereed citations

for i in attr['Clean_Feature_Name']:
    q = ads.SearchQuery(q=i, keyword='mars', year = '1971-1980', fl=['bibcode'], rows=2000)
    bibcodes = [j.bibcode for j in q]
    metrics_query = ads.MetricsQuery(bibcodes)
    try:        
        metrics_response = metrics_query.execute()
        np7180.append(metrics_response['basic stats']['number of papers'])
        ncp7180.append(metrics_response['citation stats']['number of citing papers'])
        nsc7180.append(metrics_response['citation stats']['number of self-citations'])
        tnc7180.append(metrics_response['citation stats']['total number of citations'])
        tnrc7180.append(metrics_response['citation stats']['total number of refereed citations'])
        print(i + " added")
    except:
        np7180.append(0)
        ncp7180.append(0)
        nsc7180.append(0)
        tnc7180.append(0)
        tnrc7180.append(0)
        print(i + " added with exception")